name: dart_synthizer
description: Dart bindings for the Synthizer sound library.
version: 1.0.0
homepage: https://www.github.com/chrisnorman7/dart_synthizer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^1.1.2

dev_dependencies:
  ffigen: ^3.0.0
  pedantic: ^1.11.1
  test: ^1.17.10

ffigen:
  output: "lib/synthizer_bindings.dart"
  name: "DartSynthizer"
  description: "Bindings for the Synthizer audio library"
  headers:
    entry-points:
      - "synthizer/include/synthizer.h"
      - "synthizer/include/synthizer_constants.h"
