name: dart_synthizer
version: 0.8.0
description: Dart bindings for the Synthizer sound library.
repository: https://www.github.com/chrisnorman7/dart_synthizer

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  ffi: ^1.1.2
  meta: ^1.7.0
  path: ^1.8.1
  quiver: ^3.0.1

dev_dependencies:
  dart_style: ^2.2.0
  ffigen: ^4.0.0
  lints: ^1.0.1
  test: ^1.17.10

ffigen:
  output: "lib/src/synthizer_bindings.dart"
  name: "DartSynthizer"
  description: "Bindings for the Synthizer audio library"
  headers:
    entry-points:
      - "synthizer/include/synthizer.h"
      - "synthizer/include/synthizer_constants.h"
