name: dart_synthizer
version: 0.10.0
description: Dart bindings for the Synthizer sound library.
repository: https://www.github.com/chrisnorman7/dart_synthizer

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ffi: ^1.2.1
  meta: ^1.8.0
  path: ^1.8.2
  quiver: ^3.1.0

dev_dependencies:
  dart_style: ^2.2.3
  ffigen: ^6.0.0
  lints: ^2.0.0
  test: ^1.21.1

ffigen:
  output: "lib/src/synthizer_bindings.dart"
  name: "DartSynthizer"
  description: "Bindings for the Synthizer audio library"
  headers:
    entry-points:
      - "synthizer/include/synthizer.h"
      - "synthizer/include/synthizer_constants.h"
  functions:
    include:
      - "syz_.*"
