name: dart_synthizer
version: 0.11.3
description: Dart bindings for the Synthizer sound library.
repository: https://www.github.com/chrisnorman7/dart_synthizer

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  ffi: ^2.0.1
  meta: ^1.8.0
  path: ^1.8.2
  quiver: ^3.2.1

dev_dependencies:
  dart_style: ^2.2.4
  ffigen: ^11.0.0
  lints: ^3.0.0
  test: ^1.21.6

ffigen:
  output: "lib/src/synthizer_bindings.dart"
  name: "DartSynthizer"
  description: "Bindings for the Synthizer audio library"
  headers:
    entry-points:
      - "synthizer/include/synthizer.h"
      - "synthizer/include/synthizer_constants.h"
  functions:
    include:
      - "syz_.*"
